name: "Kubernetes KinD Cluster"
description: "Create a KinD (Kubernetes in Docker) cluster with a container image registry and optional addons (Knative)"
author: "Container Tools developers"
branding:
  color: blue
  icon: cloud
inputs:
  version:
    description: "The KinD version to use (default: v0.10.0)"
  config:
    description: "The path to the KinD config file"
  node_image:
    description: "The Docker image for the cluster nodes"
  cluster_name:
    description: "The name of the cluster to create (default: kind)"
  wait:
    description: "The duration to wait for the control plane to become ready (default: 60s)"
  log_level:
    description: "The log level for KinD"
  registry:
    description: "Configures an insecure registry on kind-registry:5000 to be used with KinD (default: true)"
  kubectl_version:
    description: "The version of kubectl to use (default: v1.20.0)"
  knative_serving:
    description: "The version of Knative Serving to install on the Kind cluster (not installed by default - example: v0.20.0)"
  knative_kourier:
    description: "The version of Knative Net Kourier to install on the Kind cluster (not installed by default - example: v0.20.0)"
  knative_eventing:
    description: "The version of Knative Eventing to install on the Kind cluster (not installed by default - example: v0.20.0)"
runs:
  using: "node12"
  main: "main.js"
  post: "cleanup.js"
